### PR TITLE
Add optional copy_packages task

### PR DESCRIPTION
**Pull request by mroach**
Copies the vendor/ dir from the previous release. This can bring a significant reduction in deploy time when there are many dependencies. Note that using this feature makes vendor/ cumulative. That is, as packages are dropped they will not be automatically removed from vendor/ on deploy.

Adapted for Capistrano 3 from http://capifony.org/cookbook/speeding-up-deploy.html

### CODE REVIEW

**Comment by sergeyklay** [comment]
:+1:

**Comment by swalkinshaw** [comment]
There's an official Capistrano to generically handle this use case: https://github.com/capistrano/copy-files

**Comment by mroach** [comment]
@swalkinshaw Would you accept a pull request adding instructions to the README on how to use copy-files then to achieve this? I can't imagine I'm alone in finding the dependency install time to be a problem.

**Comment by swalkinshaw** [comment]
@mroach sure, that's a good idea.

**Pull request closed without merging**
